"""changing the username and email unique off

Revision ID: b852b8241612
Revises: 78cf5c3d1dc8
Create Date: 2025-07-19 12:19:06.366317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b852b8241612'
down_revision: Union[str, Sequence[str], None] = '78cf5c3d1dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
